import Foundation

enum CommandCatalog {
    static let all: [CommandSeed] = [
        CommandSeed(id: "mac-pwd", category: "目录", name: "pwd", syntax: "pwd", explanation: "显示当前所在目录的绝对路径，迷路时先执行它。", example: "pwd", platform: "macOS", tags: ["路径", "当前位置"]),
        CommandSeed(id: "mac-ls", category: "目录", name: "ls", syntax: "ls [选项] [路径]", explanation: "列出目录内容；-l 看详情，-a 包含隐藏文件，-h 让大小易读。", example: "ls -lah ~/Documents", platform: "macOS", tags: ["目录", "文件", "隐藏文件"]),
        CommandSeed(id: "mac-cd", category: "目录", name: "cd", syntax: "cd [路径]", explanation: "切换当前目录；~ 表示用户主目录，.. 表示上一级，- 返回上次目录。", example: "cd ~/Documents/Codex", platform: "macOS", tags: ["切换目录", "路径"]),
        CommandSeed(id: "mac-mkdir", category: "文件", name: "mkdir", syntax: "mkdir -p 路径", explanation: "创建目录；-p 会一次创建缺失的父目录，已存在时不报错。", example: "mkdir -p ~/Code/c-study/day01", platform: "macOS", tags: ["新建", "文件夹"]),
        CommandSeed(id: "mac-touch", category: "文件", name: "touch", syntax: "touch 文件", explanation: "创建空文件或更新已有文件的修改时间。", example: "touch hello.c", platform: "macOS", tags: ["新建", "文件"]),
        CommandSeed(id: "mac-cp", category: "文件", name: "cp", syntax: "cp -R 来源 目标", explanation: "复制文件或目录；复制目录通常需要 -R。", example: "cp -R ~/Code/demo ~/Backup/demo", platform: "macOS", tags: ["复制", "备份"]),
        CommandSeed(id: "mac-mv", category: "文件", name: "mv", syntax: "mv 来源 目标", explanation: "移动或重命名文件与目录。目标已存在时可能被覆盖，操作前确认路径。", example: "mv old.c main.c", platform: "macOS", tags: ["移动", "重命名"]),
        CommandSeed(id: "mac-rm", category: "文件", name: "rm", syntax: "rm -i 文件", explanation: "删除文件；-i 删除前询问。macOS 的 rm 默认不会进入废纸篓。", example: "rm -i old.c", platform: "macOS", tags: ["删除", "危险命令"]),
        CommandSeed(id: "mac-chmod", category: "权限", name: "chmod", syntax: "chmod 644 文件", explanation: "修改权限。常见值：644 普通文件，755 可执行脚本，600 私密文件。", example: "chmod 755 run.sh", platform: "macOS", tags: ["权限", "rwx", "可执行"]),
        CommandSeed(id: "mac-open", category: "工具", name: "open", syntax: "open [文件或应用]", explanation: "用 macOS 默认应用打开文件，或打开 Finder、URL。", example: "open -a \"Visual Studio Code\" hello.c", platform: "macOS", tags: ["VS Code", "Finder", "打开文件"]),
        CommandSeed(id: "mac-clang", category: "编译", name: "clang", syntax: "clang -Wall -Wextra -o 输出 源文件.c", explanation: "使用 Clang 编译 C 程序；-Wall -Wextra 打开常用警告，调试加 -g。", example: "clang -Wall -Wextra -g -o hello hello.c && ./hello", platform: "macOS", tags: ["C", "编译", "调试"]),
        CommandSeed(id: "mac-man", category: "帮助", name: "man", syntax: "man 命令", explanation: "查看命令手册。输入 q 退出，/关键词 搜索。", example: "man ls", platform: "macOS", tags: ["帮助", "手册"]),
        CommandSeed(id: "mac-brew", category: "工具", name: "brew", syntax: "brew install 软件包", explanation: "Homebrew 包管理器，用于安装开发工具和命令行程序。", example: "brew install git gcc", platform: "macOS", tags: ["Homebrew", "安装"]),
        CommandSeed(id: "mac-git-status", category: "Git", name: "git status", syntax: "git status", explanation: "查看工作区和暂存区状态，是提交前最常用的安全检查。", example: "git status --short", platform: "macOS", tags: ["版本控制", "Git"]),
        CommandSeed(id: "mac-git-init", category: "Git", name: "git init", syntax: "git init", explanation: "在当前目录创建 Git 仓库。", example: "mkdir demo && cd demo && git init", platform: "macOS", tags: ["Git", "仓库"]),
        CommandSeed(id: "mac-git-commit", category: "Git", name: "git commit", syntax: "git add 文件 && git commit -m \"说明\"", explanation: "把暂存区内容保存为一个版本记录。", example: "git add hello.c && git commit -m \"完成第一个 C 程序\"", platform: "macOS", tags: ["Git", "提交"]),

        CommandSeed(id: "linux-uname", category: "系统", name: "uname", syntax: "uname -a", explanation: "查看内核名称、版本和硬件架构。", example: "uname -a", platform: "Linux", tags: ["内核", "架构"]),
        CommandSeed(id: "linux-lsblk", category: "磁盘", name: "lsblk", syntax: "lsblk -f", explanation: "树状显示块设备、文件系统、UUID 和挂载点。", example: "lsblk -f", platform: "Linux", tags: ["磁盘", "分区", "挂载"]),
        CommandSeed(id: "linux-df", category: "磁盘", name: "df", syntax: "df -h", explanation: "查看各文件系统空间使用情况，-h 使用 GB/MB 单位。", example: "df -h", platform: "Linux", tags: ["磁盘", "空间"]),
        CommandSeed(id: "linux-du", category: "磁盘", name: "du", syntax: "du -sh 目录", explanation: "统计目录占用空间，-s 只显示汇总，-h 易读。", example: "du -sh ~/projects/* | sort -h", platform: "Linux", tags: ["目录大小", "磁盘"]),
        CommandSeed(id: "linux-ps", category: "进程", name: "ps", syntax: "ps aux", explanation: "列出进程；aux 能查看所有用户、包含终端与无终端进程。", example: "ps aux | grep ssh", platform: "Linux", tags: ["进程", "PID"]),
        CommandSeed(id: "linux-top", category: "进程", name: "top", syntax: "top", explanation: "实时查看 CPU、内存和进程；按 q 退出。", example: "top -o %CPU", platform: "Linux", tags: ["性能", "进程"]),
        CommandSeed(id: "linux-kill", category: "进程", name: "kill", syntax: "kill -TERM PID", explanation: "向进程发送信号。先 TERM 请求退出，必要时再使用 KILL。", example: "kill -TERM 12345", platform: "Linux", tags: ["信号", "进程"]),
        CommandSeed(id: "linux-systemctl", category: "服务", name: "systemctl", syntax: "sudo systemctl status 服务", explanation: "查看、启动、停止或设置服务开机启动。", example: "sudo systemctl status nginx", platform: "Linux", tags: ["systemd", "服务"]),
        CommandSeed(id: "linux-journalctl", category: "日志", name: "journalctl", syntax: "journalctl -u 服务 --since \"1 hour ago\"", explanation: "读取 systemd 日志，-u 指定服务，-f 实时跟随。", example: "journalctl -u nginx -f", platform: "Linux", tags: ["日志", "systemd", "排错"]),
        CommandSeed(id: "linux-ss", category: "网络", name: "ss", syntax: "ss -tulpn", explanation: "查看 TCP/UDP 监听端口及所属进程，是 netstat 的现代替代。", example: "sudo ss -tulpn", platform: "Linux", tags: ["端口", "监听", "网络"]),
        CommandSeed(id: "linux-ip", category: "网络", name: "ip", syntax: "ip addr show", explanation: "查看或配置网络接口、地址与路由。", example: "ip addr show && ip route", platform: "Linux", tags: ["IP", "网卡", "路由"]),
        CommandSeed(id: "linux-curl", category: "网络", name: "curl", syntax: "curl -i URL", explanation: "发送 HTTP 请求，-i 显示响应头，-X 指定方法。", example: "curl -i https://example.com", platform: "Linux", tags: ["HTTP", "调试", "网络"]),
        CommandSeed(id: "linux-ping", category: "网络", name: "ping", syntax: "ping -c 4 主机", explanation: "发送 ICMP 探测包，检查网络可达性与往返时间。", example: "ping -c 4 1.1.1.1", platform: "Linux", tags: ["连通性", "延迟"]),
        CommandSeed(id: "linux-apt", category: "包管理", name: "apt", syntax: "sudo apt install 软件包", explanation: "Debian/Ubuntu 包管理命令。安装前通常先 apt update。", example: "sudo apt update && sudo apt install build-essential", platform: "Linux", tags: ["Ubuntu", "软件包"]),
        CommandSeed(id: "linux-grep", category: "文本", name: "grep", syntax: "grep -RIn \"文本\" 路径", explanation: "递归搜索文本；-R 递归，-I 跳过二进制，-n 显示行号。", example: "grep -RIn \"main\" src/", platform: "Linux", tags: ["搜索", "文本", "管道"]),
        CommandSeed(id: "linux-find", category: "文本", name: "find", syntax: "find 路径 -name \"模式\"", explanation: "按名称、类型、时间等条件查找文件，可结合 -exec 处理结果。", example: "find . -name \"*.c\" -type f", platform: "Linux", tags: ["查找", "文件"]),
        CommandSeed(id: "linux-sed", category: "文本", name: "sed", syntax: "sed -n '1,20p' 文件", explanation: "逐行处理文本；-i 可直接修改文件，使用前建议先备份。", example: "sed -n '1,20p' access.log", platform: "Linux", tags: ["文本", "替换"]),
        CommandSeed(id: "linux-awk", category: "文本", name: "awk", syntax: "awk '{print $1, $3}' 文件", explanation: "按字段处理文本；$1 是第一列，NF 是字段数，NR 是行号。", example: "awk -F: '{print $1}' /etc/passwd", platform: "Linux", tags: ["列", "文本", "统计"]),
        CommandSeed(id: "linux-xargs", category: "文本", name: "xargs", syntax: "命令 | xargs -n1 参数命令", explanation: "把标准输入转换成后续命令的参数。文件名含空格时优先用 -print0 和 xargs -0。", example: "find . -name \"*.tmp\" -print0 | xargs -0 rm -i", platform: "Linux", tags: ["管道", "批量处理"]),
        CommandSeed(id: "linux-chmod", category: "权限", name: "chmod", syntax: "chmod 640 文件", explanation: "修改文件权限；数字分别表示所有者、组、其他人的读写执行权限。", example: "chmod 600 ~/.ssh/id_ed25519", platform: "Linux", tags: ["权限", "安全"]),
        CommandSeed(id: "linux-chown", category: "权限", name: "chown", syntax: "sudo chown 用户:组 文件", explanation: "修改文件所有者和所属组。", example: "sudo chown -R dev:dev /srv/app", platform: "Linux", tags: ["所有者", "权限"]),
        CommandSeed(id: "linux-useradd", category: "用户", name: "useradd", syntax: "sudo useradd -m -s /bin/bash 用户名", explanation: "创建用户；-m 创建主目录，-s 指定登录 Shell。", example: "sudo useradd -m -s /bin/bash learner", platform: "Linux", tags: ["用户", "账户"]),
        CommandSeed(id: "linux-passwd", category: "用户", name: "passwd", syntax: "sudo passwd 用户名", explanation: "设置或修改用户密码，普通用户可修改自己的密码。", example: "sudo passwd learner", platform: "Linux", tags: ["密码", "用户"]),
        CommandSeed(id: "linux-crontab", category: "计划任务", name: "crontab", syntax: "crontab -e", explanation: "编辑当前用户的定时任务。每行顺序是分、时、日、月、星期、命令。", example: "0 3 * * * /home/dev/backup.sh", platform: "Linux", tags: ["cron", "定时"]),
        CommandSeed(id: "linux-tcpdump", category: "网络", name: "tcpdump", syntax: "sudo tcpdump -i 网卡 -nn", explanation: "抓取并分析网络包；-nn 不解析主机名和端口名，便于看清原始信息。", example: "sudo tcpdump -i eth0 -nn port 80", platform: "Linux", tags: ["抓包", "TCP", "排错"]),
        CommandSeed(id: "linux-strace", category: "调试", name: "strace", syntax: "strace -f -o trace.log 程序", explanation: "跟踪程序发起的系统调用，定位文件、网络和权限问题。", example: "strace -f -e trace=file ./app", platform: "Linux", tags: ["系统调用", "调试"]),
        CommandSeed(id: "linux-gdb", category: "调试", name: "gdb", syntax: "gdb ./程序", explanation: "调试 C/C++ 程序。常用命令：break、run、next、step、print、backtrace。", example: "clang -g -o demo demo.c && gdb ./demo", platform: "Linux", tags: ["调试", "断点"]),
        CommandSeed(id: "linux-docker", category: "容器", name: "docker", syntax: "docker run [选项] 镜像", explanation: "运行容器；-it 分配交互终端，--rm 退出后删除容器。", example: "docker run --rm -it ubuntu:24.04 bash", platform: "Linux", tags: ["Docker", "容器"]),
        CommandSeed(id: "linux-namespace", category: "容器", name: "unshare", syntax: "sudo unshare --pid --fork --mount-proc bash", explanation: "创建新的 namespace，用于观察容器隔离的底层机制。", example: "sudo unshare --pid --fork --mount-proc bash", platform: "Linux", tags: ["namespace", "隔离"]),
        CommandSeed(id: "linux-dmesg", category: "系统", name: "dmesg", syntax: "sudo dmesg -T", explanation: "查看内核环形缓冲区日志，-T 显示可读时间。", example: "sudo dmesg -T | tail -n 30", platform: "Linux", tags: ["内核", "驱动", "日志"]),
        CommandSeed(id: "linux-lscpu", category: "系统", name: "lscpu", syntax: "lscpu", explanation: "查看 CPU 架构、核心数、线程数、缓存和虚拟化信息。", example: "lscpu", platform: "Linux", tags: ["CPU", "缓存"]),
        CommandSeed(id: "linux-free", category: "系统", name: "free", syntax: "free -h", explanation: "查看物理内存与交换空间使用情况。", example: "free -h", platform: "Linux", tags: ["内存", "swap"]),
        CommandSeed(id: "linux-nginx", category: "服务", name: "nginx", syntax: "nginx -t", explanation: "测试 Nginx 配置文件语法；修改配置后先测试再重载。", example: "sudo nginx -t && sudo systemctl reload nginx", platform: "Linux", tags: ["Web", "Nginx", "配置"]),
        CommandSeed(id: "linux-ufw", category: "安全", name: "ufw", syntax: "sudo ufw allow 22/tcp", explanation: "管理 Ubuntu 防火墙规则；启用前务必允许 SSH，避免把自己锁在外面。", example: "sudo ufw allow OpenSSH && sudo ufw enable", platform: "Linux", tags: ["防火墙", "SSH", "安全"]),
        CommandSeed(id: "linux-getenforce", category: "安全", name: "getenforce", syntax: "getenforce", explanation: "查看 SELinux 当前模式；Ubuntu 通常使用 AppArmor。", example: "getenforce", platform: "Linux", tags: ["SELinux", "安全"]),
        CommandSeed(id: "linux-aa-status", category: "安全", name: "aa-status", syntax: "sudo aa-status", explanation: "查看 AppArmor 配置文件和进程限制状态。", example: "sudo aa-status", platform: "Linux", tags: ["AppArmor", "安全"])
    ]
}
