import Foundation

enum ConceptCatalog {
    static var all: [Concept] {
        [
            Concept(id: "pointer", name: "指针", aliases: ["pointer", "地址", "解引用"], category: "C 与内存", summary: "指针保存对象地址，类型决定解引用和指针算术的单位。", details: "理解指针要同时确认地址、指向类型、有效生命周期和长度。空指针、悬空指针、越界和释放后访问是主要风险。数组名在许多表达式中退化为首元素地址，但这不代表数组和指针完全相同。", relatedTutorialIDs: ["tutorial-c-foundation", "tutorial-architecture", "tutorial-os-systems"]),
            Concept(id: "memory-layout", name: "内存布局", aliases: ["memory layout", "栈区", "堆区"], category: "C 与内存", summary: "进程地址空间通常由代码、全局数据、堆、栈和共享库等区域组成。", details: "局部变量通常位于栈，动态分配通常来自堆，字面量和全局数据位于不同只读或可写段。布局是概念模型，具体地址和增长方向由平台与实现决定，不能依赖偶然地址。", relatedTutorialIDs: ["tutorial-c-foundation", "tutorial-architecture", "tutorial-os-systems"]),
            Concept(id: "stack-frame", name: "栈帧", aliases: ["stack frame", "调用栈"], category: "架构", summary: "函数调用时保存返回地址、参数、局部变量和寄存器恢复信息的栈区域。", details: "栈帧帮助理解调用约定、递归、局部变量生命周期和崩溃回溯。返回局部变量地址之所以危险，是因为函数返回后该栈帧可以立即被其他调用复用。", relatedTutorialIDs: ["tutorial-architecture", "tutorial-os-systems"]),
            Concept(id: "compilation", name: "编译", aliases: ["compile", "编译器"], category: "工具链", summary: "把源代码转换为目标文件并检查语法、类型和部分语义的过程。", details: "编译不是运行。警告通常表示潜在错误，错误会阻止产物生成。常用流程是预处理、编译、汇编和链接；分步执行有助于定位宏展开、符号和库问题。", relatedTutorialIDs: ["tutorial-mac-terminal", "tutorial-c-foundation", "tutorial-architecture", "tutorial-compiler"]),
            Concept(id: "linking", name: "链接", aliases: ["linker", "链接器"], category: "工具链", summary: "把多个目标文件和库合并，解析符号并生成可执行文件。", details: "未定义符号、重复符号和库顺序是常见链接错误。静态链接把代码复制进产物，动态链接在加载时解析共享库，二者在体积、更新和部署上有不同取舍。", relatedTutorialIDs: ["tutorial-architecture", "tutorial-compiler"]),
            Concept(id: "process", name: "进程", aliases: ["process", "PID"], category: "操作系统", summary: "拥有独立虚拟地址空间和系统资源的运行实例。", details: "进程包含代码、数据、文件描述符、线程和内核状态。fork 创建新进程，exec 替换地址空间，wait 回收退出状态。进程隔离强，但创建和通信成本通常高于线程。", relatedTutorialIDs: ["tutorial-os-systems", "tutorial-linux-l3", "tutorial-linux-l4"]),
            Concept(id: "thread", name: "线程", aliases: ["thread", "pthread"], category: "并发", summary: "进程内的调度单位，共享地址空间但拥有独立栈和寄存器上下文。", details: "线程共享数据带来高性能和同步风险。互斥锁保护临界区，条件变量等待状态，join 回收线程资源。共享状态越多，越需要明确同步协议。", relatedTutorialIDs: ["tutorial-os-systems", "tutorial-linux-l4"]),
            Concept(id: "mutex", name: "互斥锁", aliases: ["mutex", "锁", "临界区"], category: "并发", summary: "保证同一时刻只有一个执行流进入临界区。", details: "锁必须覆盖完整读写操作，并在所有路径释放。持锁执行慢 I/O、嵌套获取不同锁或提前返回忘记解锁，会造成性能下降和死锁。", relatedTutorialIDs: ["tutorial-os-systems", "tutorial-linux-l4"]),
            Concept(id: "virtual-memory", name: "虚拟内存", aliases: ["virtual memory", "页表", "缺页"], category: "操作系统", summary: "为进程提供连续虚拟地址，并由 MMU 映射到物理页。", details: "虚拟内存实现隔离、按需分配、共享库和 mmap。虚拟地址合法不代表物理页已分配，访问未映射页或缺页处理失败会触发段错误。", relatedTutorialIDs: ["tutorial-computer-basics", "tutorial-os-systems", "tutorial-linux-l6"]),
            Concept(id: "file-descriptor", name: "文件描述符", aliases: ["fd", "file descriptor"], category: "系统编程", summary: "进程打开文件、管道和 socket 等资源后得到的小整数索引。", details: "fd 指向进程打开文件表中的条目，多个 fd 可指向同一打开文件。必须检查返回值和错误码，并在所有路径 close，否则会耗尽资源。", relatedTutorialIDs: ["tutorial-linux-l4", "tutorial-networking"]),
            Concept(id: "system-call", name: "系统调用", aliases: ["syscall", "系统调用"], category: "操作系统", summary: "用户程序请求内核提供服务的受控入口。", details: "open、read、fork、socket 等系统调用跨越用户态和内核态。失败通常返回 -1 并设置 errno。strace 能观察调用顺序、参数和错误。", relatedTutorialIDs: ["tutorial-os-systems", "tutorial-linux-l4", "tutorial-linux-l6"]),
            Concept(id: "signal", name: "信号", aliases: ["signal", "SIGTERM", "SIGINT"], category: "系统编程", summary: "内核或进程异步通知目标进程发生事件的机制。", details: "TERM 请求退出，KILL 不可捕获，INT 常由 Ctrl+C 产生。信号处理函数应保持短小并只修改异步安全标志，复杂工作放回主循环。", relatedTutorialIDs: ["tutorial-linux-l3", "tutorial-linux-l4"]),
            Concept(id: "ipc", name: "进程间通信", aliases: ["IPC", "管道", "共享内存"], category: "系统编程", summary: "管道、FIFO、消息队列、共享内存和信号量等多进程协作机制。", details: "不同 IPC 在方向、生命周期、同步和性能上不同。共享内存最快，但必须配合锁或信号量；管道简单，但容量和 EOF 行为需要理解。", relatedTutorialIDs: ["tutorial-linux-l4", "tutorial-os-systems"]),
            Concept(id: "socket", name: "Socket", aliases: ["套接字", "socket API"], category: "网络", summary: "统一表示网络通信端点的文件描述符接口。", details: "服务器通常执行 socket、bind、listen、accept，客户端执行 connect。TCP 是字节流，不保留应用消息边界，协议必须定义长度或分隔符。", relatedTutorialIDs: ["tutorial-networking", "tutorial-linux-l4"]),
            Concept(id: "tcp", name: "TCP", aliases: ["传输控制协议", "三次握手"], category: "网络", summary: "面向连接、可靠、有序的字节流传输协议。", details: "TCP 通过序号、确认、重传和流量控制提供可靠传输，但不保证应用消息边界，也不保证连接永久可用。超时和重连需要应用层策略。", relatedTutorialIDs: ["tutorial-networking", "tutorial-linux-l5"]),
            Concept(id: "http", name: "HTTP", aliases: ["HTTP/1.1", "状态码", "请求头"], category: "网络", summary: "客户端和服务端之间的请求-响应应用协议。", details: "请求包含方法、路径、头部和可选正文；响应包含状态码、头部和正文。Content-Length 或分块编码决定正文边界，HTTPS 在 HTTP 与传输层之间加入 TLS。", relatedTutorialIDs: ["tutorial-networking", "tutorial-linux-l5"]),
            Concept(id: "dns", name: "DNS", aliases: ["域名解析", "resolver"], category: "网络", summary: "把域名解析为 IP 地址的分层命名系统。", details: "DNS 查询可能经过本地缓存、递归解析器、根和权威服务器。解析成功只说明得到地址，仍需检查路由、端口、TLS 和 HTTP 响应。", relatedTutorialIDs: ["tutorial-networking", "tutorial-linux-l5"]),
            Concept(id: "hash-table", name: "哈希表", aliases: ["hash map", "散列表"], category: "数据结构", summary: "通过哈希函数把键映射到桶，平均提供常数时间查找。", details: "碰撞不可避免，需要链地址法或开放寻址。负载因子过高会增加碰撞，扩容时要重新分布键。哈希与相等判断必须保持一致。", relatedTutorialIDs: ["tutorial-dsa", "tutorial-linux-l6"]),
            Concept(id: "tree", name: "树", aliases: ["二叉树", "B+ 树", "平衡树"], category: "数据结构", summary: "由节点和父子关系组成的层次结构。", details: "二叉搜索树依赖有序不变量，普通树可能退化；平衡树维持高度。B+ 树把多个键放入页节点，适合磁盘和数据库索引。", relatedTutorialIDs: ["tutorial-dsa", "tutorial-database"]),
            Concept(id: "graph", name: "图", aliases: ["graph", "邻接表", "拓扑排序"], category: "数据结构", summary: "由顶点和边表示对象及关系的结构。", details: "BFS 适合无权最短路径和按层扩展，DFS 适合连通性、回溯和拓扑排序。稀疏图通常使用邻接表，稠密图可使用邻接矩阵。", relatedTutorialIDs: ["tutorial-dsa", "tutorial-networking"]),
            Concept(id: "complexity", name: "复杂度", aliases: ["大 O", "Big O", "时间复杂度"], category: "算法", summary: "描述输入规模增长时时间或空间成本的增长趋势。", details: "复杂度必须结合数据分布、常数因子、缓存和实际瓶颈理解。大 O 不是运行时间，也不能替代性能测量。", relatedTutorialIDs: ["tutorial-dsa", "tutorial-linux-l6"]),
            Concept(id: "cache", name: "缓存", aliases: ["cache", "缓存命中", "局部性"], category: "计算机系统", summary: "把较慢层的数据保存在较快层，减少重复访问成本。", details: "缓存需要容量、淘汰、失效和一致性策略。缓存命中依赖时间与空间局部性，但会增加内存、复杂性和旧数据风险。", relatedTutorialIDs: ["tutorial-architecture", "tutorial-linux-l6", "tutorial-database"]),
            Concept(id: "assembly", name: "汇编", aliases: ["assembly", "x86-64", "指令"], category: "架构", summary: "与机器指令接近、仍可被汇编器处理的低级表示。", details: "汇编揭示寄存器、栈帧、调用约定和优化结果。阅读时应结合 ABI、源位置和编译器优化级别，不能把某个编译器输出当成语言规范。", relatedTutorialIDs: ["tutorial-architecture", "tutorial-compiler"]),
            Concept(id: "register", name: "寄存器", aliases: ["register", "rax", "rip", "rsp"], category: "架构", summary: "CPU 内部速度最快、数量很少的存储位置。", details: "寄存器保存运算数、地址和 CPU 状态。调用约定规定参数、返回值和被调用者保存寄存器，栈指针 rsp 和指令指针 rip 对调试尤其重要。", relatedTutorialIDs: ["tutorial-architecture", "tutorial-os-systems"]),
            Concept(id: "kernel", name: "内核", aliases: ["kernel", "Linux kernel"], category: "操作系统", summary: "管理处理器、内存、设备和系统调用的核心软件。", details: "内核运行在高权限态，通过 /proc、/sys、日志和工具暴露状态。内核错误影响大，调试通常需要谨慎环境和专门的工具。", relatedTutorialIDs: ["tutorial-os-systems", "tutorial-linux-l6"]),
            Concept(id: "namespace", name: "Namespace", aliases: ["命名空间", "PID namespace"], category: "容器", summary: "隔离进程可见资源视图的内核机制。", details: "PID、mount、network、UTS 和 user namespace 分别隔离进程、挂载、网络和用户身份。Namespace 改变看到的内容，不负责限制使用量。", relatedTutorialIDs: ["tutorial-linux-l7", "tutorial-os-systems"]),
            Concept(id: "cgroup", name: "Cgroup", aliases: ["控制组", "cgroup v2"], category: "容器", summary: "限制、统计和隔离进程组资源使用的内核机制。", details: "CPU、内存、I/O 和进程数可以通过 cgroup 限制。Docker 的资源参数最终会映射到 cgroup，容器中看到的宿主机资源信息需要结合限制解释。", relatedTutorialIDs: ["tutorial-linux-l7", "tutorial-linux-l6"]),
            Concept(id: "transaction", name: "事务", aliases: ["ACID", "commit", "rollback"], category: "数据库", summary: "一组必须原子提交或回滚的数据库操作。", details: "事务提供原子性、一致性、隔离性和持久性。隔离级别决定并发异常和性能，长事务会保留旧版本并增加清理压力。", relatedTutorialIDs: ["tutorial-database", "tutorial-linux-l4"]),
            Concept(id: "database-index", name: "数据库索引", aliases: ["B+ tree index", "复合索引"], category: "数据库", summary: "为特定查询路径维护的辅助数据结构。", details: "索引加速读取但增加空间和写入成本。复合索引通常遵循最左前缀原则，上线前应使用执行计划验证，而不是盲目添加。", relatedTutorialIDs: ["tutorial-database", "tutorial-dsa"]),
            Concept(id: "lexer", name: "词法分析", aliases: ["lexer", "tokenizer", "token"], category: "编译原理", summary: "把字符流切分为有类型的 token 并记录源位置。", details: "长匹配优先，空白通常丢弃，错误要带行列信息。词法分析只识别词法单元，不判断它们是否组成合法语法。", relatedTutorialIDs: ["tutorial-compiler"]),
            Concept(id: "parser", name: "语法分析", aliases: ["parser", "递归下降"], category: "编译原理", summary: "根据文法把 token 组织成语法树或 AST。", details: "递归下降解析器为每个非终结符写函数，运营商优先级由分层规则表达。解析器遇错必须前进或恢复，否则会无限循环。", relatedTutorialIDs: ["tutorial-compiler"]),
            Concept(id: "ast", name: "抽象语法树", aliases: ["AST", "语法树"], category: "编译原理", summary: "描述程序语法结构的树形中间表示。", details: "AST 省略括号和无关标点，保留语义结构。节点可携带源位置，后续语义分析、解释器和代码生成都基于 AST。", relatedTutorialIDs: ["tutorial-compiler"]),
            Concept(id: "ir", name: "中间表示", aliases: ["IR", "三地址码", "SSA"], category: "编译原理", summary: "位于源语言和目标机器之间、便于分析和优化的程序表示。", details: "三地址码把复杂表达式拆成简单操作，SSA 限制每个变量只赋值一次。常量折叠、传播和死代码删除都在 IR 上执行。", relatedTutorialIDs: ["tutorial-compiler", "tutorial-architecture"]),
            Concept(id: "mmap", name: "mmap", aliases: ["内存映射", "MAP_SHARED"], category: "系统编程", summary: "把文件或匿名内存映射到进程虚拟地址空间。", details: "mmap 适合大文件随机访问和共享内存，但仍需处理页对齐、映射长度、保护标志和 munmap。超过文件大小的访问可能触发 SIGBUS。", relatedTutorialIDs: ["tutorial-linux-l4", "tutorial-os-systems"]),
            Concept(id: "epoll", name: "epoll", aliases: ["事件循环", "I/O 多路复用"], category: "系统编程", summary: "Linux 上管理大量文件描述符事件的高扩展性接口。", details: "epoll_ctl 维护关注集合，epoll_wait 返回就绪事件。边沿触发模式通常要求一次读取到 EAGAIN，否则剩余数据可能不再触发通知。", relatedTutorialIDs: ["tutorial-linux-l4", "tutorial-networking"])
        ]
    }
}
